import { Annotation } from '@langchain/langgraph';

export const GraphAnnotation = Annotation.Root({
  engineRunId: Annotation(),
  dailyKey: Annotation(),
  runType: Annotation(),
  runScope: Annotation(),
  runMode: Annotation(),
  limit: Annotation(),
  minScore: Annotation(),
  strategy: Annotation(),
  targetReady: Annotation(),
  maxAttempts: Annotation(),
  attempts: Annotation(),
  lastAttempted: Annotation(),
  lastGeneratedOk: Annotation(),
  topicsCollected: Annotation(),
  topicsSelected: Annotation(),
  articlesGenerated: Annotation(),
  articlesValidated: Annotation(),
  factChecksCompleted: Annotation(),
  channelOutputsGenerated: Annotation(),
  readyCount: Annotation(),
  qualityFailedCount: Annotation(),
  dedupeRejected: Annotation(),
  seoGeoScored: Annotation(),
  skipSeoGeoScore: Annotation(),
  noMoreCandidates: Annotation(),
  warnings: Annotation({
    reducer: (a, b) => [...(a || []), ...(b || [])],
    default: () => [],
  }),
  errors: Annotation({
    reducer: (a, b) => [...(a || []), ...(b || [])],
    default: () => [],
  }),
  nextActions: Annotation({
    reducer: (a, b) => [...(a || []), ...(b || [])],
    default: () => [],
  }),
});

export function initialGraphState(input = {}) {
  return {
    engineRunId: input.engineRunId || null,
    dailyKey: input.dailyKey || null,
    runType: input.runType || 'batch',
    runScope: input.runScope || 'batch',
    runMode: input.runMode || 'start',
    limit: Number(input.limit || 1),
    minScore: Number(input.minScore || 80),
    strategy: input.strategy || 'balanced',
    targetReady: Number(input.targetReady || input.limit || 1),
    maxAttempts: Number(input.maxAttempts || 15),
    attempts: 0,
    lastAttempted: 0,
    lastGeneratedOk: 0,
    topicsCollected: 0,
    topicsSelected: 0,
    articlesGenerated: 0,
    articlesValidated: 0,
    factChecksCompleted: 0,
    channelOutputsGenerated: 0,
    readyCount: 0,
    qualityFailedCount: 0,
    dedupeRejected: 0,
    seoGeoScored: 0,
    skipSeoGeoScore: Boolean(input.skipSeoGeoScore),
    noMoreCandidates: false,
    warnings: [],
    errors: [],
    nextActions: [],
  };
}
